## 行列演算の基礎


$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [ ]:
#ベクトルの定義
#行列の定義
#転置
#逆行列
#行列積

In [1]:
import numpy as np

In [5]:
#ベクトルの定義
x = np.array([[1],[2],[3]])
x

[[1]
 [2]
 [3]]


In [7]:
#行列の定義
X = np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [9]:
#転置
Xt = X.T
Xt

array([[1, 3],
       [2, 4]])

In [13]:
#逆行列
#linear algebra: 線形代数
X_inv = np.linalg.inv(X)
X_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [16]:
#行列積
XX_inv = np.dot(X,X_inv)
XX_inv

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

# よくある間違い

In [17]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [18]:
x.T

array([1, 2, 3])

In [20]:
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [21]:
x.T

array([[1],
       [2],
       [3]])

# Numpyでよく使う処理

In [28]:
X = np.array([
    [2,3,4],
    [1,2,3]
])
X

array([[2, 3, 4],
       [1, 2, 3]])

In [29]:
row,col = X.shape
row

2

In [30]:
col

3

In [31]:
for x in X:
    print(x)

[2 3 4]
[1 2 3]


$\boldsymbol{X} =
$$
\begin{bmatrix}
1 & 2 & 3 \\\ 
1 & 2 & 5 \\\
1 & 3 & 4 \\\
1 & 5 & 9
\end{bmatrix}
$$
$
,
$\boldsymbol{y} =
$$
\begin{bmatrix}
1 \\\ 
5 \\\
6 \\\
8
\end{bmatrix}
$$
$
のとき

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [34]:
X = np.array([
    [1,2,3,],
    [1,2,5,],
    [1,3,4,],
    [1,5,9,],
])
X

array([[1, 2, 3],
       [1, 2, 5],
       [1, 3, 4],
       [1, 5, 9]])

In [60]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
y

array([[1],
       [5],
       [6],
       [8]])

In [50]:
Xt = X.T
Xt

array([[1, 1, 1, 1],
       [2, 2, 3, 5],
       [3, 5, 4, 9]])

In [64]:
XtX = np.dot(Xt,X)
XtX

array([[  4,  12,  21],
       [ 12,  42,  73],
       [ 21,  73, 131]])

In [67]:
XtX_inv = np.linalg.inv(XtX)

In [68]:
XtX_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [63]:
Xty = np.dot(Xt,y)
Xty

array([[ 20],
       [ 70],
       [124]])

In [70]:
w = np.dot(XtX_inv,Xty)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

# Scikit-learnで実装

In [71]:
import sklearn

In [72]:
#juypter nootbookでのインストール方法
#!pip install scikit-learn

$\boldsymbol{X} =
$$
\begin{bmatrix}
1 & 2 & 3 \\\ 
1 & 2 & 5 \\\
1 & 3 & 4 \\\
1 & 5 & 9
\end{bmatrix}
$$
$
,
$\boldsymbol{y} =
$$
\begin{bmatrix}
1 \\\ 
5 \\\
6 \\\
8
\end{bmatrix}
$$
$
のとき

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [74]:
#重回帰分析のみ読み込み
from sklearn.linear_model import LinearRegression

In [80]:
#モデルの宣言
# model = LinearRegression()
model = LinearRegression(fit_intercept=False)

In [81]:
#モデルの学習←パラメータの調整
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [82]:
#調整後のパラメータ
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [83]:
model.intercept_

0.0

In [85]:
#予測精度←決定係数
model.score(X,y)

0.6923076923076923

In [86]:
#予測値の計算
x = np.array([
    [1,2,3]
])

In [88]:
y_pred = model.predict(x)
y_pred

array([[3.]])